callback when playlist finishes
derhuerst/mplayer-wrapper pull request #1
Opened 2018-05-18 12:07 UTC by MortenHe

added callback when playlist finishes

2018-05-18 14:47 UTC, derhuerst commented on index.js
> +			return out.emit('playlist-finished')
To keep the event names consistent, please use `playlist-finish`.

2018-05-18 14:47 UTC, derhuerst commented on index.js
> +		.pipe(byLine.createStream())
Please keep the indentation as before.

2018-05-18 14:47 UTC, derhuerst commented on index.js
> +			env: process.env,
Please keep the indentation as before.

2018-05-18 14:49 UTC, derhuerst requested changes
Thanks so far! I only have minor comments.

2018-05-23 10:36 UTC, derhuerst commented on index.js
> +module.exports = createPlayer
almost done! 😉

2018-05-23 10:55 UTC, closed without merging

2018-05-23 10:55 UTC, MortenHe commented
i tried again